baseURL: "https://hugo-profile.netlify.app"
languageCode: "en-us"
title: "Jacobo Profile"
theme: hugo-profile

Paginate: 3
disqusShortname: gurusabarish
googleAnalytics: G-DWJJVE27WD

markup:
  goldmark:
    renderer:
      unsafe: true

deployment:
  order:
    - .png$
    - .jpg$
    - .gif$
    - .svg$
  targets:
    - URL: 's3://jacobogonzalez-hugo-website?region=us-east-1'
  matchers:
    - pattern: ^.+\.(js|css|png|jpg|gif|svg|ttf)$
      cacheControl: 'max-age=630720000, no-transform, public'
      gzip: true
    - pattern: ^.+\.(html|xml|json)$
      gzip: true

Menus:
  # main:
  #   - identifier: certifications
  #     name: Certifications
  #     title: Achived Certifications
  #     url: /certifications
  #     weight: 1

    # - identifier: gallery
    #   name: Gallery
    #   title: Blog posts
    #   url: /gallery
    #   weight: 2

    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Jacobo Gonzalez"
  description: My Professional and Tech site as Resume and Portfolio
  # staticPath: ""  # The path to serve the static files from
  favicon: "/images/fav.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    disableThemeToggle: false
    # defaultTheme: "light" # dark

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    brandLogo: "/images/logo2.png" # Logo for the brand | default is the favicon variable
    brandName: "Jacobo Gonzalez" # Brand name for the brand | default is the title variable

  #   menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
  #     disableAchievements: true
  #     disableContact: true

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Jacobo."
    subtitle: "I build and desing things for the cloud"
    content: "A passionate Cloud and IT Engineer. I tend to make use of modern technologies to assess and build solutions that fulfills expectations and functions correctly."
    image: /images/profile2-02.jpg
    button:
      enable: true
      name: "Resume"
      url: "https://resume.io/r/JmlnzFvMp"
      download: true
      newPage: true
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/Jacobog3
        - icon: fab fa-twitter
          url: https://twitter.com/jacobog3X
      customIcons:
        - icon: /images/logo2.png
          url: "http://jacobogonzalez.com"

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/profile1.jpg"
    content: |-
      DevOps and Network Engineer with over 10+ years of experience in networking and IT Technology. Expert within a wide variety of security, engineering, networking, cloud and operating system software. 
      I am a highly responsible, proactive, and self-taught person. I am motivated by the challenges and learning new things, with that I been able to develop my leadership skills and helped other people. I am currently working as a DevOps engineer at [Triumph Tech](https://www.triumphtech.com). 
      I am currently working on helping customers that wants to migrate to the cloud.
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "AWS"
        - "Terraform"
        - "CI/CD Pipelines"
        - "Containers"
        - "Cloudformation"
        - "Cloud Migration Tools"

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "DevOps Engineer"
        company: "Triumph Tech"
        companyUrl: "https://www.triumphtech.com"
        date: "Apr 2022 - present"
        featuredLink:
          enable: false
          name: "View the project"
          url: "https://example.com"
        info:
          enable: false
        content: | 
          I am currently working as a Consultant for Triumph Tech, supporting customer in their transition to the cloud. 
          - Helping customer builnding their CI/CD Pipelines, IaC, containerization primarily and designing and coding the right solution for their business needs. 
          - Focusing on all products that AWS can provide.

      - job: "Coordinador de Redes e Ingenieria"
        company: "Innova Telco"
        companyUrl: "https://innovatelco.net/"
        date: "Jul 2021 - Apr 2022"
        featuredLink:
          enable: false
          url: "https://example.com"
        info:
          enable: false
          content: I worked as a software developer for more than one year in Amazon.
        content: |
          Responsible of the implementing, designing and support for the core Network Infrastructure of the ISP. 
          - Build the first DevOps team, migrating their local web environment to the cloud, using new cloud technologies for better performance implementing containerization, EKS clustering, terraform as IaC and HA solution for their product in AWS.
          - Major Achievement: Build the MPLS Core Network for the delivery of L3VPNs.
      - job: "L2 Engineer"
        company: "ITS Infocom"
        companyUrl: "https://www.itsinfocom.com"
        date: "Sep 2019 - Nov 2020"
        info:
          enable: false
        featuredLink:
          enable: false
          url: "https://example.com"
        content: |
          I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.
          - Lead backend developer for a product.
          - Created a frontend design for a product.
      - job: "Network Audit Engineer"
        company: Conduent
        companyUrl: "https://www.conduent.com/"
        date: "Sep 2017 - Aug 2019"
        info:
          enable: false
        featuredLink:
          enable: false
          url: "https://example.com"
        content: |
          I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.
          - Lead backend developer for a product.
          - Created a frontend design for a product.
      - job: "Senior Network Engineer"
        company: "Allied Global"
        companyUrl: "https://alliedglobal.com/"
        date: "Jan 2016 - Sep 2017"
        info:
          enable: false
        featuredLink:
          enable: false
          url: "https://example.com"
        content: |
          I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.
          - Lead backend developer for a product.
          - Created a frontend design for a product.
      - job: "Pre Sales and Post Sales Engineer"
        company: "Tigo"
        companyUrl: "https://www.tigo.com.gt"
        date: "Feb 2012 - Dec 2015"
        info:
          enable: false
        content: "I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city."

  # Education
  education:
    enable: true
    # title: "Custom Name"
    # index: true
    items:
      - title: "Master of Business Administration with minor in Finance"
        school:
          name: "Universidad Francisco Marroquin"
          url: "https://ufm.edu"
        date: "2017 - 2018"
        GPA: "93 out of 100"
        content: |
          - Magna Cum Laude Distinction. 
            
      - title: "Maestria en Tecnologias de la Informacion"
        school:
          name: "Universidad Galileo"
          url: "https://galileo.edu"
        date: "2011 - 2012"
        GPA: "92 out of 100"
        content: |-
          - Magna Cum Laude Distinction.
        featuredLink:
          enable: false
          name: "My academic record"
          url: "https://example.com"
      - title: "Postgrado en Seguridad Informatica"
        school:
          name: "Universidad Galileo"
          url: "https://galileo.edu"
        date: "2012 - 2012"
        GPA: "97 out of 100"
        content:
        featuredLink:
          enable: false
          name: "My academic record"
          url: "https://example.com"
      - title: "Ingenieria en Telecomunicaciones"
        school:
          name: "Universidad Galileo"
          url: "https://galileo.edu"
        date: "2007 - 2010"
        GPA: "80 out of 100"
        content: |-
          - Obtain academic scholarship for academic excellence.
          - Worked as a junior developer for University website.
        featuredLink:
          enable: false
          name: "My academic record"
          url: "https://example.com"
  
  # Certifications
  certifications:
    enable: true
    title: "Certifications"
    items:
      - title: AWS Certified Solutions Architect – Professional
        image: /images/aws-sap.png
        url: https://www.credly.com/badges/47d3a2a8-a945-4173-a07f-56c13af0bf5c/public_url
      - title: AWS Certified Advanced Networking – Specialty
        image: /images/aws-ans.png
        url: https://www.credly.com/badges/49c95958-8070-4586-af75-544961cbf718/public_url
      - title: AWS Certified Solutions Architect – Associate
        image: /images/aws-saa.png
        url: https://www.credly.com/badges/ed5c383f-11c3-4056-95ec-ef54293c95e5/public_url
      - title: Microsoft Certified Azure Fundamentals
        image: /images/microsoft-azure-fundamentals.png
        url: https://www.credly.com/badges/630305a6-83c6-4f48-870f-c852784b5eb6/public_url
      - title: Cisco Certified Network Professional Enterprise (CCNP Enterprise)
        image: /images/ccnp.png
        url: https://www.credly.com/badges/236b07cd-350f-4039-ae88-05115bb9220d/public_url

  # Achievements
  achievements:
    enable: false
    title: "Certifications"
    items:
      - title: AWS Certified Solutions Architect – Professional
        image: /images/aws-sap.png
        url: https://www.credly.com/badges/47d3a2a8-a945-4173-a07f-56c13af0bf5c/public_url
      - title: Facebook Hackathon Winner
        content: Developed a product using Artificial Intelligence.
      - title: Hugo Profile
        content: Developed a theme and getting 1K+ downloads per month.
        url: "https://github.com/gurusabarish/hugo-profile"
      - title: Microsoft Imagine Runner
        content: We are developed a product which can help others.
      - title: Google Summer of Code
        content: Contributed to a open source project.
        url: https://example.com

  # projects
  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: Hugo Profile
        content: A highly customizable and mobile first Hugo template for personal portfolio and blog.
        image: /images/projects/profile.png
        featured:
          name: Visit Site
          link: https://jacobogonzalez.com
        links:
          - icon: fab fa-github
            url: https://github.com/Jacobog3/resume-hugo-s3
  
  #Contact
  contact:
    enable: true
    #title: "Custom name"
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: jacobo.lgonzalez@gmail.com
    btnName: Mail me

  footer:
    recentPosts: false
    socialNetworks:
      github: https://github.com/Jacobog3
      linkedin: https://www.linkedin.com/in/jacobog/
      twitter: https://twitter.com/jacobog3X